vips_source_resolvers:
  basic_filename:
    images_path: /images

kakadu:
  check_loader: true # Verifies that actually using Kakadu in vips.

vips:
  jpeg_quality: 90

public_cache: 24 # Cache-Control header, in hours. False to disable.