vips_source_resolvers:
  basic_filename:
    images_path: /images

kakadu:
  check_loader: true # Verifies that actually using Kakadu in vips.

vips:
  jpeg_quality: 90

public_cache: 24 # Cache-Control header, in hours. False to disable.

file_cache:
  path: tmp/file-cache
  enabled: true

iiif:
  profile_level: level2
  # See https://cantaloupe-project.github.io/manual/5.0/endpoints.html#IIIFImageAPI3
  min_size: 64 # Minimum size that will be used in info.json `sizes` keys.
  min_tile_size: 1024 # Minimum size that will be used in info.json `tiles` keys.
  